Fix checkout and add workflow check
Signed-off-by: Joonas Rautiola <joonas.rautiola@unikie.com>

diff --git a/.github/workflows/test-ghaf-infra.yml b/.github/workflows/test-ghaf-infra.yml
--- a/.github/workflows/test-ghaf-infra.yml
+++ b/.github/workflows/test-ghaf-infra.yml
@@ -47,6 +47,34 @@ jobs:
     steps:
       - run: true
 
+  warn-for-workflow-changes:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          ref: ${{ github.event.pull_request.head.sha || github.ref }}
+          fetch-depth: 2
+
+      - name: Check if workflow is modified
+        id: build-yml-changed
+        uses: tj-actions/changed-files@v40
+        with:
+          files: .github/workflows/test-ghaf-infra.yml
+
+      - name: Send warning
+        run: |
+          # Not changed
+          if [ "${{ steps.build-yml-changed.outputs.any_changed }}" == "true" ]; then
+            echo "::error::"\
+                 "This change edits workflow file '.github/workflows/test-ghaf-infra.yml' from"\
+                 "an internal PR. Raising this error (but not failing the job) to notify"\
+                 "that the build workflow change will only take impact after merge."\
+                 "Therefore, you need to manually test the change (perhaps in a"\
+                 "forked repo) before merge to make sure the change does not break"\
+                 "anything."\
+            exit 1
+          fi
+
   tests:
     # Don't run unless authorization was successful
     needs: [authorize]
@@ -55,6 +83,9 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v4
+        with:
+            ref: ${{ github.event.pull_request.head.sha || github.ref }}
+            fetch-depth: 0
 
       - uses: cachix/install-nix-action@v27
         with:
